allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  less: true
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
  nx: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@sneat/*'
  - '@angular-devkit/architect@0.2102.20'
  - '@angular-devkit/core@21.2.20'
  - '@angular/build@21.2.20'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - less
  - nx
  - unrs-resolver
